build:
  nodes:
    # Edge Zemit Build
    zemit:
      root_path: './'
      services:
        mysql: latest
        redis: 6
      resources:
        cpus: 1
      environment:
        selenium: true
        google_chrome:
          use_latest: true
        timezone: 'America/New_York'
        hosts:
          core.zemit.local: 127.0.0.1
        apache2:
          modules: ['rewrite']
          sites:
            zemit:
              host: core.zemit.local # also make sure to add under "hosts" above
              web_root: public/
              rules:
                - 'RewriteEngine On'
                - 'RewriteCond %{REQUEST_FILENAME} !-d'
                - 'RewriteCond %{REQUEST_FILENAME} !-f'
                - 'RewriteRule ^(.*)$ index.php?_url=/$1 [QSA,L]'
        php:
          version: 7.4
          # @link https://pecl.php.net/
          pecl_extensions:
            - psr
            - redis
            - memcached
            - apcu
            - phalcon-4.1.2
          ini:
            memory_limit: -1
      dependencies:
        before:
          - composer self-update
        after:
          - composer require --dev phalcon/ide-stubs:4.1.0
          - composer require --dev phpunit/phpunit
          - composer require --dev squizlabs/php_codesniffer
      tests:
        stop_on_failure: false
        override:
          - command: php-scrutinizer-run --enable-security-analysis
          - command: phpcs-run
          - command: ./vendor/bin/phpunit
            coverage:
              file: phpunit-clover.xml
              format: php-clover
      cache:
        disabled: false
        directories:
          - ~/.composer
          - ~/.npm
          - vendor/
          - node_modules/
checks:
  php: true
filter:
  excluded_paths:
    - 'tests/' # test suite
    - 'src/Migrations/' # autogenerated
    - 'src/Models/Base/' # autogenerated
    - 'src/Function/Dump.php' # debug features
  dependency_paths:
    - 'vendor/'
    - 'node_modules/'
