version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/php8.2-fpm-alpine-phalcon5.6.2/Dockerfile
    image: zemit-php
    container_name: zemit-php
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: zemit-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: zemit
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: zemit
    networks:
      - app-network
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: zemit-redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
